language: android
sudo: required
os: osx
before_install:
  - openssl aes-256-cbc -k "$keyEncryption" -in android/app/hiprock.jks.enc  -d -a -out
  android/app/hiprock.jks
  - nvm install 6
  - node --version
  - wget http://dl.google.com/android/ndk/android-ndk-r10e-darwin-x86_64.bin
  - chmod +x android-ndk-r10e-darwin-x86_64.bin
  - ./android-ndk-r10e-darwin-x86_64.bin | grep ndk-build.cmd
  - export ANDROID_NDK=`pwd`/android-ndk-r10e
  - echo $ANDROID_NDK
  - bash ci/.travis-android-license-bugfix.sh
  - echo y | android update sdk --no-ui --all --filter ${ANDROID_EMULATOR},${ANDROID_PKGS},build-tools-23.0.1
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-23.0.1
  - echo y | android update sdk -u -a -t build-tools-23.0.2
  - echo y | android update sdk -u -a -t build-tools-25.0.0
  - echo y | android update sdk -u -a -t build-tools-25.0.1
  - echo y | android update sdk -u -a -t build-tools-26.0.1
  - echo y | android update sdk -u -a -t build-tools-26.0.2
  - echo y | android update sdk -u -a -t android-23
  - echo y | android update sdk -u -a -t android-25
  - echo y | android update sdk -u -a -t extra-google-google_play_services
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository
  - echo y | android update sdk -u -a -t addon-google_apis-google-26

install:
  - npm install
script:
  - source run.sh
